name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: swift:${{ matrix.swift }}

    strategy:
      matrix:
        swift: ["6.2"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - run: swift --version

      - run: swift build

      - run: swift test
